version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
 jenkins:
  image: rebootshen/jenkins
  container_name: jenkins
  ports:
    - "8090:8090"
    - "8022:22"
    - "80:80"
    - "8019:8019"
    - "9000:9000"
    - "25:25"
    - "7777:7777"
  networks:
    - prodnetwork
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes_from:
    - DATA
#    - "$VOLUMES_FROM"
  links:
    - artifactory
    - tomcat
    - mysql
    - selenium-hub
    - opensuse
    
# worker_java:
#  image: rebootshen/jenkins
#  restart: always
#  ports:
#    - "8190:8090"
#  networks:
#    - prodnetwork
#  volumes_from:
#    - DATA_SLAVE_JAVA
#  links:
#    - artifactory
#    - tomcat
#    - mysql
#    - selenium-hub
#  environment:
#    - JAVA_OPTS=-Xmx2048m
#    - JENKINS_NAME=worker
#    - JENKINS_RETRY=10
#  env_file:
#    - secret.txt
    
# worker_c:
#  image: rebootshen/jenkins
#  restart: always
#  ports:
#    - "8290:8090"
#  networks:
#    - prodnetwork
#  volumes_from:
#    - DATA_SLAVE_C
#  links:
#    - artifactory
#    - tomcat
#    - mysql
#    - selenium-hub
#  environment:
#    - JAVA_OPTS=-Xmx2048m
#    - JENKINS_NAME=worker
#    - JENKINS_RETRY=10
#  env_file:
#    - secret.txt
 opensuse:
  image: rebootshen/opensuse-cpp
  container_name: opensuse
  ports:
    - "8122:22"
  networks:
    - prodnetwork
  volumes_from:
    - DATA
    
 artifactory:
  image: docker.bintray.io/jfrog/artifactory-oss
  container_name: artifactory
  ports:
    - "8081:8081"
  networks:
    - prodnetwork
  volumes_from:
    - DATA
    
 tomcat:
  image: rebootshen/tomcat
  container_name: tomcat
  ports:
    - "8080:8080"
  networks:
    - prodnetwork
  links:
    - mysql
  environment:
    - CATALINA_OUT=/logs/catalina.out
  volumes_from:
    - DATA
    
 mysql:
  image: mysql:5.7
  container_name: mysql
  ports:
    - "3306:3306"
  networks:
    - prodnetwork
  environment:
    - MYSQL_ROOT_PASSWORD=root
  volumes_from:
    - DATA

 selenium-hub:
  image: selenium/hub:2.53.0
  container_name: selenium-hub
  ports:
    - "4444:4444"
  networks:
    - prodnetwork
 nodeff:
  image: selenium/node-firefox:2.53.0
  container_name: firefox1
  ports:
    - 5900
  networks:
    - prodnetwork
  environment:
   - HUB_PORT_4444_TCP_ADDR=selenium-hub
  links:
    - selenium-hub
 nodechrome:
  image: selenium/node-chrome:2.53.0
  container_name: chrome1
  ports:
    - 5900
  networks:
    - prodnetwork
  environment:
   - HUB_PORT_4444_TCP_ADDR=selenium-hub
  links:
    - selenium-hub

 DATA:
  image: rebootshen/demo-data
  container_name: DATA
  networks:
    - prodnetwork
  volumes:
    - /var/opt/jfrog/artifactory
    - /var/lib/jenkins
    - /var/lib/mysql
    - /logs
    - /backup
    - /git
    - /svn
    - /sonatype-work
    - /c/Users/Sam/Documents/DEV/puppet-server/modules:/etc/puppet/modules
    - /c/Users/Sam/Documents/DEV/puppet-server/manifests:/etc/puppet/manifests
#  command: /bin/true
  
# DATA_SLAVE_JAVA:
#  image: rebootshen/demo-data
#  container_name: DATA_SLAVE_JAVA
#  networks:
#    - prodnetwork
#  volumes:
#    - /var/opt/jfrog/artifactory
#    - /var/lib/jenkins
#    - /var/lib/mysql
#    - /logs
#    - /backup
#    - /git
#  command: /bin/true
  
# DATA_SLAVE_C:
#  image: rebootshen/demo-data
#  container_name: DATA_SLAVE_C
#  networks:
#    - prodnetwork
#  volumes:
#    - /var/opt/jfrog/artifactory
#    - /var/lib/jenkins
#    - /var/lib/mysql
#    - /logs
#    - /backup
#    - /git
#  command: /bin/true
  